name: robprog
channels:
  - defaults
  - conda-forge   # Efficient with big database but take time to run
dependencies:
  - python==3.11
  - pip           # Quicker but normally have conflict with versions
  - pip:  
    - -r requirements.txt


